### ISSUE TITLE
질문!

### ISSUE THREAD

**Issue by jiji-hoon96** [nninyeong/pokemon#8]
https://github.com/nninyeong/pokemon/blob/a15cd22cd85b1b3136c028ef5cff1efbce42b252/pokemon/src/components/PokemonCard.jsx#L14

e.target.closest('.cardButton')을 사용해볼 수 있지 않을까요??

**Comment by nninyeong** [comment]
@jiji-hoon96 튜터님 안녕하세요! 적용해보고 댓글 남기려했는데 이번 MBTI 테스트 과제가 너무 정신없이 진행되는 바람에.. 이제야 적용해봤습니다🥲 이벤트 버블링을 막고싶었던 의도였는데 알려주신 방법을 사용하면 좀 더 간결하게 처리할 수 있었네요!! 감사합니다!
